[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
async-trait = "0.1.68"
miette = "5.9.0"
once_cell = "1.18.0"
regex = "1.8.4"
relative-path = "1.8.0"
rustc-hash = "1.1.0"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.97"
serde_yaml = "0.9.21"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
tracing = { version = "0.1.37" }
