[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
async-trait = "0.1.72"
miette = "5.10.0"
once_cell = "1.18.0"
regex = "1.9.1"
relative-path = "1.8.0"
rustc-hash = "1.1.0"
serde = { version = "1.0.176", features = ["derive"] }
serde_json = "1.0.104"
serde_yaml = "0.9.25"
thiserror = "1.0.44"
tokio = { version = "1.29.1", features = ["full"] }
tracing = { version = "0.1.37" }
